[[bin]]
name = "hello_remote_world"
path = "Source/main.rs"

[dev-dependencies]
postgres = "0.19"

[package]
authors = ["VS Code <vscode@microsoft.com>"]
name = "hello_remote_world"
version = "0.1.0"
